# NORESTE 2
# PM 2.5 and PM 10 Analysis
A test of model performance to analyze the time series behaviour of particulate matter.

## Placing of directory

In [1]:
import os
from pathlib import Path
print("Directorio actual:", os.getcwd())

current_dir = Path.cwd()
project_root = current_dir
while not (project_root / '.git').exists() and project_root != project_root.parent:
    project_root = project_root.parent
    os.chdir("..")

print(f"Raíz del proyecto: {project_root}")
print("CWD cambiado a raíz del proyecto")

Directorio actual: /home/ferrus/Documents/university/semester_x/MA2003B/PROYECTO_MA2003B/notebooks/03_models
Raíz del proyecto: /home/ferrus/Documents/university/semester_x/MA2003B/PROYECTO_MA2003B
CWD cambiado a raíz del proyecto

## Library imports and mastertable

In [2]:
import pandas as pd
import numpy as np
import src.data_prep.table_generator as tables_gen
from src.data_prep import imputation

path_master = "data/processed/master_table.csv"
df_master   = pd.read_csv(path_master)

/tmp/ipykernel_8514/2755314451.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_master   = pd.read_csv(path_master)

## PM 2.5 and PM 10 tables

Table generation for pm2.5 and pm10 measures on station **noreste2**.

In [3]:
df_table_pm25 = tables_gen.orchestrate_contaminant_station_table(df_master, "pm2.5", "noreste2")
df_table_pm10 = tables_gen.orchestrate_contaminant_station_table(df_master, "pm10", "noreste2")

In [4]:
df_table_pm25.head()

   hour_of_year  pm2.5_2022  pm2.5_2023  pm2.5_2024
0             1       137.0        67.0       351.0
1             2       113.0       101.0       351.0
2             3       141.0       143.0       331.0
3             4       168.0       154.0       286.0
4             5       139.0       166.0       178.0

In [5]:
df_table_pm10.head()

   hour_of_year  pm10_2022  pm10_2023  pm10_2024
0             1      182.0       93.0      484.0
1             2      166.0      162.0      484.0
2             3      184.0      209.0      429.0
3             4      201.0      220.0      426.0
4             5      216.0      219.0      262.0

## Generación de intervalos de confianza PM2.5 2022, 2023, 2024.

In [ ]:
df_pm25_2022 = df_table_pm25[['hour_of_year', "pm2.5_2022"]]

imputer_pm25_2022 = imputation.TimeSeriesImputer(df_table_pm25)
# Aplicar todas las estrategias a una columna específica
df_pm25_2022_imputed = imputer_pm25_2022.bootstrap_imputation_df('pm2.5_2022')
df_pm25_2023_imputed = imputer_pm25_2022.bootstrap_imputation_df('pm2.5_2023')
df_pm25_2024_imputed = imputer_pm25_2022.bootstrap_imputation_df('pm2.5_2024')

## Generación de intervalos de confianza PM10 2022, 2023, 2024.

In [ ]:
df_pm10_2022 = df_table_pm10[['hour_of_year', "pm10_2022"]]

imputer_pm10_2022 = imputation.TimeSeriesImputer(df_table_pm10)
# Aplicar todas las estrategias a una columna específica
df_pm10_2022_imputed = imputer_pm10_2022.bootstrap_imputation_df('pm10_2022')
df_pm10_2023_imputed = imputer_pm10_2022.bootstrap_imputation_df('pm10_2022')
df_pm10_2024_imputed = imputer_pm10_2022.bootstrap_imputation_df('pm10_2022')